os:
- linux
services:
- docker
language: node_js
node_js:
- 10.13.0
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
env:
  global:
  - NODE_VERSION=10.13.0
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: I/F7VV26jzH2Do1LmDLmrQDRydtSNIJ4KOfGVbNOvkres98m4XdiNMefsXcdbssIw5NxmYzqRfCn7rao6WEEuSFT8+7MvP4AGpdi9Tu5r1U0hIMZrK8t0qOfTnWTQvvQ2krFlHx2c1QWdGoBAol184PSJk594TD7r1VE895lxaylY00k+CniW0npwrw0RFapu/QHrX6C1/i1traeFwm6bNlaX7TAFZZg8YHAUrBY9j+9o3xzVx6n89h0hlI1GaJjDp9jKLZm4d829afq414ScvrQzERnXpl7qqNUxwlFvCwcUF/afoO1cV5n3GmDdBTBCQKFH+RBadHzBe7jYuUx2qTTLnoZoZ4z4DYd2Yc7IB+PYLxeSbU7cZq0/2Qf76wKzVSz3Azut+GaCpRh9D/D5lIvAxfxLi6XW1D52FmCe9Fv6spcwKhs0yZQc6j0yTNm2goJYpqM9Lon0sQOGlwg8BjHzsiCTm+TF/5FD28a3U/pYl4s5hbllfnWxdm/uH2dMVwh9gjaVHCaLEpyTceKOVc74Cceh9QOfb5n4mJMEf3o8Lol/ejYdT63KhU4dorOIJOlsbVLvMkl3tCfbL2A7V6GLRexhztl+HARoshdM+yjkV8y9A3mVEliJyhaZxqO3O/KHwd95k3HkzMjadZMf9ohW9CjhioeIFWxBtjpdH8= #$DOCKER_USER
  - secure: EMIRfXGgxr4/LRNwZFnGOTrnitIcqLVS//Bjlsx157TOjihLs7ubd3R6UuR/8IYgvcQIhCb55VmCV8sdCxxkK9I2eNg1YE3dtVUc2AW3DTkzVwpPGtm5sI0eIz6HsIl+9OS8YZIgeTFcTk2f0V9Rg+9fE5QjRcDtrB7mCSgDW/IQP1Qlvk8e9cL8+y9bhugqX/SPCQLBxfhSLjWjATcqNd+AZn76ZCbbFlC1Di/nyCcYTp28cg9bawshkbVV1sLDyENBBYc9P3p6UH2kD4rojbrT+koQON7wnBWPKp1VAzPhf06hGs+qvCwMwl8hBJmFeL1MP+mgsNGCF6pe3fSEdS/urdleEgC7MSJUxLFcnA3QT0mNCTLCb1cgVq7yhIVZstoISWH0S62ujCPFYF8yn9F+cHvRuYDWR7o3vEd+QzrJ3T8LnpEMI1RgehMj3cO52T+B5lQGGE6ys0X5uE22HdK2RrF9lyxcyJy8yU9Yf4bMfkL37klzsmfA10AulNLKB/YnpUKl6uPIppKj4xR9CkIS7WWFerM+CnovML8q9spopQ00kNP/ExysTccpNfcpGTpbxFDQ2H+UjpunOrKEu9Am1OiB+RnxyHABk/kpjEzuzi6ljclAYKCJvFI2BZXhWJ4Y0BuD3qu2HmpvEH8dN7n5vmvsRfjaB9hZZnfXqPY= #$DOCKER_PASS
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- nvm install $NODE_VERSION
- npm install -g npm
- node -v
- npm -v
install:
- npm install
script:
- chmod +x mvnw
- "./mvnw package -DskipTests=true -Pprod jib:dockerBuild"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=latest
- export IMAGE_NAME=gustavocaraciolo/luulpos
- docker tag luulpos $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
